// Builds the full school list from the U.S. College Scorecard data
// (location, public/private, 2yr/4yr, tuition). Athletic data (association,
// division, sports) comes from data/athletics.json (see scripts/build-athletics.py, EADA data).
//
//   node scripts/build-data.mjs   (no API key needed: uses data/scorecard.json)
import { writeFileSync, existsSync, readFileSync, mkdirSync } from 'node:fs';

// College Scorecard institution data. CI runners get HTTP 403 from the Scorecard download hosts, so the needed
// columns are kept in data/scorecard.json (refresh ~yearly with `npm run refresh:scorecard`, run from a normal machine).
async function loadScorecard() {
  return JSON.parse(readFileSync('data/scorecard.json', 'utf8')).rows;
}

const dom = (u) => (u ?? '').toLowerCase().replace(/^https?:\/\//, '').replace(/^www\./, '').split('/')[0];
// unitid -> { association, division, sports } from scripts/build-athletics.py (EADA data)
const ath = new Map(Object.entries(JSON.parse(readFileSync('data/athletics.json', 'utf8'))));
// optional: NCAA conference names by website domain from scripts/fetch-ncaa.mjs
const conf = new Map();
if (existsSync('data/athletics.csv')) {
  for (const line of readFileSync('data/athletics.csv', 'utf8').trim().split('\n').slice(1)) {
    const [domain, , , conference, , athleticUrl] = line.split(',');
    conf.set(domain, { conference, athleticUrl });
  }
}

// manual fixes for fast-changing facts: { "<unitid>": { conference, athleticsUrl, scholarshipUrl, ... } }
const overrides = existsSync('data/overrides.json') ? JSON.parse(readFileSync('data/overrides.json', 'utf8')) : {};
// Conference/region names per association from data/<assoc>-conferences.csv (columns: name,state,conference).
// naia: generated by scripts/fetch-naia.py. njcaa / cccaa / nwac: add the CSV by hand (see README) and it is picked up automatically.
const normName = (n) => n.toLowerCase().replace(/&/g, 'and').replace(/[–]/g, '-').replace(/\bthe\b|[.,'’]/g, '')
  .replace(/\bst\b/g, 'saint').replace(/\buniversity\b|\bcollege\b/g, '').replace(/[^a-z0-9]+/g, '');
const confRows = { NAIA: [], NJCAA: [], CCCAA: [], NWAC: [] };
for (const assoc of Object.keys(confRows)) {
  const file = `data/${assoc.toLowerCase()}-conferences.csv`;
  if (!existsSync(file)) continue;
  for (const line of readFileSync(file, 'utf8').trim().split(/\r?\n/).slice(1)) {
    const m = line.match(/^(?:"([^"]*)"|([^,]*)),([A-Z]{2}),(.*)$/);
    if (m) confRows[assoc].push({ name: m[1] ?? m[2], state: m[3], conf: m[4].replace(/^"|"$/g, '') });
  }
}
// exact normalized-name match, then a unique same-state prefix match ("Foo University" vs "Foo University-Main Campus")
function listedConference(assoc, name, state) {
  const rows = confRows[assoc] ?? [];
  const n = normName(name);
  const exact = rows.find((r) => r.state === state && normName(r.name) === n);
  if (exact) return exact.conf;
  const hits = rows.filter((r) => r.state === state && normName(r.name).length >= 8 && (n.startsWith(normName(r.name)) || normName(r.name).startsWith(n)));
  return hits.length === 1 ? hits[0].conf : undefined;
}

const out = [];
for (const r of await loadScorecard()) {
  const a = ath.get(r.UNITID);
  if (!a || r.CURROPER !== '1' || !['1', '2', '3'].includes(r.PREDDEG)) continue; // only operating schools with a known athletic program
  const c = conf.get(dom(r.INSTURL));
  const num = (v) => (v && !isNaN(Number(v)) ? Number(v) : null);
  out.push({
    id: r.UNITID, name: r.INSTNM, level: r.PREDDEG === '3' ? '4year' : '2year',
    control: r.CONTROL === '1' ? 'public' : 'private', city: r.CITY, state: r.STABBR,
    lat: num(r.LATITUDE) ?? undefined, lng: num(r.LONGITUDE) ?? undefined, ...a,
    conference: (a.association === 'NCAA' ? c?.conference : undefined) || listedConference(a.association, r.INSTNM, r.STABBR),
    athleticsUrl: a.association === 'NCAA' && c?.athleticUrl ? `https://${c.athleticUrl}` : undefined,
    athleticScholarship: ['D1', 'D2', 'NJCAA-D1', 'NJCAA-D2', 'NAIA'].includes(a.division),
    scholarshipNote: a.division === 'D3' || a.division === 'NJCAA-D3' ? 'D3はアスリート奨学金なし(学業・ニーズ型のみ)'
      : a.association === 'CCCAA' || a.association === 'NWAC' ? `${a.association}は原則アスリート奨学金なし`
      : a.association === 'NCAA' ? 'アスリート奨学金は競技・学校により異なります(Ivy Leagueなど例外あり)' : 'アスリート奨学金は競技・学校により異なります',
    avgNetPrice: num(r.NPT4_PUB) ?? num(r.NPT4_PRIV), tuitionInState: num(r.TUITIONFEE_IN), tuitionOutOfState: num(r.TUITIONFEE_OUT),
    website: /^https?:/.test(r.INSTURL) ? r.INSTURL : `https://${r.INSTURL}`, verified: false,
  });
}
// Sports that EADA does not break out (cheer, dance, acrobatics & tumbling, esports ...), researched per school:
// data/extra-sports.json = { "<unitid>": [{ "name": "Cheerleading", "nameJa": "チアリーディング", "gender": "W" }] }
const extraSports = existsSync('data/extra-sports.json') ? JSON.parse(readFileSync('data/extra-sports.json', 'utf8')) : {};
// Cheer / dance / stunt / acrobatics & tumbling from data/cheer.json (USA Cheer college directory + NCAA/NAIA lists, see README):
// { "<unitid>": { cheer, cats[], stunt, club, at, dance, scholarship, url } }
const cheer = existsSync('data/cheer.json') ? JSON.parse(readFileSync('data/cheer.json', 'utf8')) : {};
for (const sc of out) {
  const c = cheer[sc.id];
  if (!c) continue;
  const add = (name, nameJa, gender) => { if (!sc.sports.some((s) => s.name === name)) sc.sports.push({ name, nameJa, gender }); };
  if (c.cheer) add('Cheerleading', 'チアリーディング', c.cats.some((x) => /Coed/.test(x)) ? 'Both' : 'W');
  if (c.dance) add('Dance', 'ダンス(競技ダンス)', 'W');
  if (c.stunt) add('STUNT', 'スタント(チア系競技)', 'W');
  if (c.at) add('Acrobatics & Tumbling', 'アクロバット&タンブリング', 'W');
  const kinds = [];
  if (c.cats.some((x) => /All Girl/.test(x))) kinds.push('競技チア(女子)');
  if (c.cats.some((x) => /Coed/.test(x))) kinds.push('競技チア(男女混合)');
  if (c.cats.some((x) => /Game Day/.test(x))) kinds.push('ゲームデイ(応援)チア');
  if (c.stunt) kinds.push('スタント(大学の正式競技チーム)');
  if (c.at) kinds.push('アクロバット&タンブリング');
  if (c.dance) kinds.push('競技ダンス');
  if (c.club && !c.stunt) kinds.push('スタントのクラブチーム');
  sc.cheerNote = `チア系: ${kinds.join('・')}。${c.scholarship ? 'プログラム掲載情報に「奨学金あり」の記載あり(額・対象は要確認)。' : '奨学金の有無は要確認。'}${c.url ? `(情報源: USA Cheerカレッジディレクトリほか。プログラムサイト: ${c.url})` : '(情報源: USA Cheerカレッジディレクトリ・NCAA/NAIA公表リスト)'}`;
}
for (const sc of out) {
  for (const x of extraSports[sc.id] ?? [])  if (!sc.sports.some((s) => s.name === x.name)) sc.sports.push(x);
}
// Maximum athletic scholarship per athlete, by association/division rules (confirm with each coach: team caps apply).
const maxAid = (sc) => {
  const cost = sc.tuitionOutOfState || sc.tuitionInState;
  const tuition = cost ? `(参考: この学校の授業料は年約${usd0(cost)})` : '';
  switch (sc.division) {
    case 'D1': if ((sc.conference ?? '').includes('Ivy')) return 'アイビーリーグは運動奨学金なし(最大$0)。学業・ニーズ型の奨学金のみ(留学生も対象となる学校が多い)。';
      return `1人あたり最大=全額(授業料・寮・食費・教材などの大学公式の総費用)。フルライド可${tuition}。`;
    case 'D2': return `1人あたり最大=全額まで可(ただしチーム全体に上限があり、多くは部分奨学金の分割)${tuition}。`;
    case 'NAIA': return `1人あたり最大=全額まで可(チーム全体に上限があり、多くは部分奨学金)${tuition}。`;
    case 'NJCAA-D1': return `1人あたり最大=授業料・諸費用・寮・食費・教材・交通費まで(フル奨学金可)${tuition}。`;
    case 'NJCAA-D2': return `1人あたり最大=授業料・諸費用・教材まで(寮・食費は対象外)${tuition}。`;
    default: return 'アスリート奨学金は出ません(最大$0)。学業・ニーズ型の奨学金は別途あり。';
  }
};
const usd0 = (n) => '$' + Math.round(n).toLocaleString('en-US');
for (const sc of out) sc.athleticScholarshipMax = maxAid(sc);
for (const sc of out) Object.assign(sc, overrides[sc.id] ?? {});
// Schools not yet researched individually get a clearly-labelled, generic estimate built from known data.
const usd = (n) => '$' + Math.round(n).toLocaleString('en-US');
const athleticAidText = (sc) => ({
  D1: 'NCAA D1は運動奨学金を出せます(学費・寮・食費・教材までの範囲、競技・チームにより差があります)。',
  D2: 'NCAA D2は運動奨学金を部分的に出せます(競技・コーチの裁量)。',
  D3: 'NCAA D3は運動奨学金がありません(学業・ニーズ型のみ)。',
  NAIA: 'NAIAは運動奨学金を出せます(競技・コーチの裁量)。',
  'NJCAA-D1': 'NJCAA D1は運動奨学金を出せます(学費・寮・食費・教材まで)。',
  'NJCAA-D2': 'NJCAA D2は運動奨学金を出せます(学費・諸費・教材まで、寮・食費は対象外)。',
  'NJCAA-D3': 'NJCAA D3は運動奨学金がありません。',
}[sc.division] ?? (sc.association === 'CCCAA' || sc.association === 'NWAC' ? `${sc.association}は原則運動奨学金がありません。` : ''));
for (const sc of out) {
  if (sc.intlAidNote) continue;
  const parts = ['【個別調査前の目安】'];
  if (sc.control === 'public' && sc.tuitionOutOfState) {
    parts.push(`公立校のため、留学生は通常、州外学生の授業料${sc.tuitionInState ? `(州内${usd(sc.tuitionInState)}/州外${usd(sc.tuitionOutOfState)}・年額目安)` : `(年額約${usd(sc.tuitionOutOfState)})`}が適用されます。`);
  } else if (sc.tuitionOutOfState || sc.tuitionInState) {
    parts.push(`授業料は年額約${usd(sc.tuitionOutOfState ?? sc.tuitionInState)}で、私立校は留学生も同額が一般的です。`);
  }
  const ath = athleticAidText(sc);
  if (ath) parts.push(ath);
  parts.push('F-1留学生は連邦・州の学費援助の対象外で、I-20発行には1年分の資金証明が必要です。留学生向け奨学金の有無・金額は、学校の国際学生課・出願ページで確認してください。');
  sc.intlAidNote = parts.join('');
  sc.intlAidAuto = true;
}
mkdirSync('public-data', { recursive: true });
const updatedAt = new Date().toISOString();
writeFileSync('public-data/schools.json', JSON.stringify({ updatedAt, schools: out }));
console.log(`wrote ${out.length} schools`);
